sudo: false

language: cpp

compiler:
    - gcc
    - clang

env:
    - CONFIGURATION=debug_x86
    - CONFIGURATION=debug_x64
    - CONFIGURATION=release_x86
    - CONFIGURATION=release_x64

install:
    - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-src.zip -O premake.zip
    - unzip -qq premake.zip
    - cd premake-5.0.0-alpha12/build/gmake.unix
    - make config=release
    - cd ../../..
    - mv premake-5.0.0-alpha12/bin/release/premake5 premake5

before_script:
    - premake5 gmake

script:
    - make -C build/Makefile config=$CONFIGURATION
    - bin/$CONFIGURATION/test

